# Generated by Django 5.0.1 on 2024-01-18 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordererName", models.CharField(max_length=100)),
                ("affiliation", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("orderStatus", models.CharField(max_length=50)),
                ("orderNumber", models.CharField(max_length=50)),
                ("creator", models.CharField(max_length=100)),
                (
                    "creationTime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modifier", models.CharField(max_length=100)),
                (
                    "lastModifiedTime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deliveryMethod", models.CharField(max_length=50)),
                ("tuxedoType", models.CharField(blank=True, max_length=100)),
                ("jacketSize", models.CharField(blank=True, max_length=50)),
                ("pantsSize", models.CharField(blank=True, max_length=50)),
                ("shirtSize", models.CharField(blank=True, max_length=50)),
                ("dressType", models.CharField(blank=True, max_length=100)),
                ("dressSize", models.CharField(blank=True, max_length=50)),
                ("ringSizeMen", models.CharField(blank=True, max_length=50)),
                ("ringSizeWomen", models.CharField(blank=True, max_length=50)),
                ("necklaceSize", models.CharField(blank=True, max_length=50)),
                ("earringType", models.CharField(blank=True, max_length=50)),
                ("bowtie", models.CharField(blank=True, max_length=50)),
                ("payerName", models.CharField(max_length=100)),
                ("relationToOrderer", models.CharField(max_length=100)),
                ("paymentMethod", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=50)),
                ("totalPayment", models.DecimalField(decimal_places=2, max_digits=10)),
                ("deposit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dressBackWidth", models.CharField(blank=True, max_length=50)),
                ("dressLength", models.CharField(blank=True, max_length=50)),
                ("jacketSleeveLength", models.CharField(blank=True, max_length=50)),
                ("jacketLength", models.CharField(blank=True, max_length=50)),
                ("pantsWaistLength", models.CharField(blank=True, max_length=50)),
                ("pantsLength", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
