# Generated by Django 5.0.1 on 2024-01-20 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordererName", models.CharField(max_length=100)),
                ("affiliation", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "orderStatus",
                    models.CharField(
                        choices=[
                            ("상담", "상담"),
                            ("주문", "주문"),
                            ("수선", "수선"),
                            ("수선입고", "수선입고"),
                            ("배송중", "배송중"),
                            ("배송완료", "배송완료"),
                            ("수령완료", "수령완료"),
                        ],
                        max_length=50,
                    ),
                ),
                ("orderNumber", models.CharField(max_length=50)),
                ("creator", models.CharField(max_length=100)),
                (
                    "creationTime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modifier", models.CharField(blank=True, max_length=100)),
                (
                    "lastModifiedTime",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "deliveryMethod",
                    models.CharField(
                        choices=[("배송", "배송"), ("직접수령", "직접수령"), ("방문수령", "방문수령")],
                        max_length=50,
                    ),
                ),
                (
                    "tuxedoType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("자켓 (R-Peaked)", "자켓 (R-Peaked)"),
                            ("자켓 (R-Shawl)", "자켓 (R-Shawl)"),
                            ("자켓 (S-Peaked)", "자켓 (S-Peaked)"),
                        ],
                        max_length=100,
                    ),
                ),
                ("jacketSize", models.CharField(blank=True, max_length=50)),
                ("pantsSize", models.CharField(blank=True, max_length=50)),
                ("shirtSize", models.CharField(blank=True, max_length=50)),
                (
                    "dressType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("드레스 (R)", "드레스 (R)"),
                            ("드레스 (S)", "드레스 (S)"),
                            ("드레스 (RM)", "드레스 (RM)"),
                        ],
                        max_length=100,
                    ),
                ),
                ("dressSize", models.CharField(blank=True, max_length=50)),
                ("ringSizeMen", models.CharField(blank=True, max_length=50)),
                ("ringSizeWomen", models.CharField(blank=True, max_length=50)),
                (
                    "necklaceSize",
                    models.CharField(
                        blank=True, choices=[("S", "S"), ("M", "M")], max_length=50
                    ),
                ),
                (
                    "earringType",
                    models.CharField(
                        blank=True,
                        choices=[("귀찌", "귀찌"), ("귀걸이", "귀걸이")],
                        max_length=50,
                    ),
                ),
                ("bowtie", models.BooleanField(blank=True, default=False)),
                ("payerName", models.CharField(max_length=100)),
                (
                    "relationToOrderer",
                    models.CharField(
                        choices=[
                            ("본인", "본인"),
                            ("부", "부"),
                            ("모", "모"),
                            ("형제", "형제"),
                            ("배우자", "배우자"),
                            ("기타", "기타"),
                        ],
                        max_length=50,
                    ),
                ),
                ("totalAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "depositKRW",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "depositJPY",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "depositUSD",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "totalDeposit",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("depositDate", models.DateField(blank=True)),
                ("balanceDate", models.DateField(blank=True)),
                ("dressBackWidth", models.CharField(blank=True, max_length=50)),
                ("dressLength", models.CharField(blank=True, max_length=50)),
                ("jacketSleeveLength", models.CharField(blank=True, max_length=50)),
                ("jacketLength", models.CharField(blank=True, max_length=50)),
                ("pantsWaistLength", models.CharField(blank=True, max_length=50)),
                ("pantsLength", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
