# Generated by Django 5.0.1 on 2024-01-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_address_alter_order_balancedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="alterationMemo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
