# Generated by Django 5.0.1 on 2024-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_alterationmemo"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paymentMethodJPY",
            field=models.CharField(
                choices=[("현금", "현금"), ("신용카드", "신용카드")],
                default="현금",
                max_length=10,
                verbose_name="선수금 결제 방법 (엔화)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentMethodKRW",
            field=models.CharField(
                choices=[("현금", "현금"), ("신용카드", "신용카드")],
                default="현금",
                max_length=10,
                verbose_name="선수금 결제 방법 (원화)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentMethodUSD",
            field=models.CharField(
                choices=[("현금", "현금"), ("신용카드", "신용카드")],
                default="현금",
                max_length=10,
                verbose_name="선수금 결제 방법 (달러)",
            ),
        ),
    ]
