# Generated by Django 5.0.1 on 2024-01-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_order_paymentmethodjpy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deliveryMethod",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="dressType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="earringType",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="necklaceSize",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="orderStatus",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentMethodJPY",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentMethodKRW",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentMethodUSD",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="relationToOrderer",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="tuxedoType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
