# Generated by Django 5.0.1 on 2024-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_order_deliverymethod_alter_order_dresstype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="spouseAffiliation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="spouseContact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="spouseName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
