# Generated by Django 5.0.1 on 2024-01-24 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_order_spouseaffiliation_order_spousecontact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paymentMethodJPY",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paymentMethodKRW",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paymentMethodUSD",
        ),
        migrations.AddField(
            model_name="order",
            name="balanceJPY",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="balanceKRW",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="balanceUSD",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentMethodBalanceJPY",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentMethodBalanceKRW",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentMethodBalanceUSD",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentMethodDepositJPY",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentMethodDepositKRW",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentMethodDepositUSD",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
